name: pytorch-tutorial
channels:
- pytorch
- defaults
dependencies:
- joblib
- jupyter
- matplotlib
- numpy
- pillow
- pip
- python=2.7
- pytorch=0.4.0
- seaborn
- scikit-image
- scipy
- six
- torchvision
- tqdm
- pip:
  - tensorboardX
  - tensorflow
